[manifest]
version = "1.0.0"
dump_lua = true
priority = 0


[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = "G.GAME.stake > 1 and {"
position = "before"
payload = '''
        RevoConfig and RevoConfig["deathcards_enabled"] and {
            label = localize('b_deathcards'),
            tab_definition_function = G.UIDEF.available_deathcards_crv,
        } or nil,
        {
            label = localize('b_gems'),
            tab_definition_function = G.UIDEF.used_gems,
        },
'''
match_indent = true