[manifest]
version = "1.0.0"
dump_lua = true
priority = 0


[[patches]]
[patches.pattern]
target = 'cardarea.lua'
pattern = '''update_hand_text({immediate = true, nopulse = true, delay = 0}, {[name] = parameter.default_value})'''
position = 'at'
payload = '''
    if name ~= "crv_dollars_mult" then
        update_hand_text({immediate = true, nopulse = true, delay = 0}, {[name] = parameter.default_value})
    end
'''
match_indent = true
[[patches]]
[patches.pattern]
target = 'cardarea.lua'
pattern = '''update_hand_text({immediate = true, nopulse = nil, delay = 0}, {[name] = '?'})'''
position = 'at'
payload = '''
    if name ~= "crv_dollars_mult" then
        update_hand_text({immediate = true, nopulse = nil, delay = 0}, {[name] = '?'})
    end
'''
match_indent = true
[[patches]]
[patches.pattern]
target = 'cardarea.lua'
pattern = '''update_hand_text({immediate = true, nopulse = nil, delay = 0}, {[name] = parameter.current})'''
position = 'at'
payload = '''
    if name ~= "crv_dollars_mult" then
        update_hand_text({immediate = true, nopulse = nil, delay = 0}, {[name] = parameter.current})
    end
'''
match_indent = true
[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''self.HUD:recalculate()'''
position = 'after'
payload = '''
if G.GAME.selected_back and G.GAME.selected_back.effect.center.crv_apply and not G.GAME.applied_crv then
    G.GAME.applied_crv = true
    G.GAME.selected_back.effect.center:crv_apply()
end
'''
match_indent = true